import { LawyerType } from "./LawyerCards";

export const lawyers: LawyerType[] = [
  {
    name: "Amit Sharma",
    experience: "10 years",
    location: "Delhi, India",
    fee: "₹1500/hr",
    languages: ["Hindi", "English"],
    rating: 4.7,
    phone: "+919876543210",
    email: "amit.sharma@example.com",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    name: "Priya Verma",
    experience: "7 years",
    location: "Mumbai, India",
    fee: "₹1200/hr",
    languages: ["Hindi", "English", "Marathi"],
    rating: 4.6,
    phone: "+919812345678",
    email: "priya.verma@example.com",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    name: "Rohit Kapoor",
    experience: "12 years",
    location: "Bangalore, India",
    fee: "₹1800/hr",
    languages: ["English", "Kannada"],
    rating: 4.8,
    phone: "+919899998877",
    email: "rohit.kapoor@example.com",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    name: "Neha Singh",
    experience: "6 years",
    location: "Chennai, India",
    fee: "₹1000/hr",
    languages: ["Tamil", "English", "Hindi"],
    rating: 4.5,
    phone: "+919811223344",
    email: "neha.singh@example.com",
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    name: "Vikram Desai",
    experience: "15 years",
    location: "Pune, India",
    fee: "₹2000/hr",
    languages: ["Marathi", "English"],
    rating: 4.9,
    phone: "+919877665544",
    email: "vikram.desai@example.com",
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    name: "Anjali Mehta",
    experience: "8 years",
    location: "Kolkata, India",
    fee: "₹1400/hr",
    languages: ["Bengali", "English", "Hindi"],
    rating: 4.6,
    phone: "+919900112233",
    email: "anjali.mehta@example.com",
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
  },
];
